# Generated by Django 5.2.1 on 2025-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.CharField(max_length=13, unique=True)),
                ('meter_serial_number', models.CharField(max_length=10)),
                ('register_id', models.CharField(max_length=2)),
                ('meter_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reading_date', models.DateField()),
            ],
        ),
    ]
