# Generated by Django 5.2.1 on 2025-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterData_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='mpan_core',
            field=models.CharField(max_length=13),
        ),
    ]
