# Generated by Django 5.2.1 on 2025-05-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterData_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='meter_reading',
            new_name='reading_value',
        ),
    ]
