# Generated by Django 5.2.1 on 2025-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterData_handler_app', '0002_rename_meter_reading_meterreading_reading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='flowFile',
        ),
    ]
