# Generated by Django 5.2.1 on 2025-05-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterData_handler_app', '0003_alter_meterreading_file_name_delete_flowfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='mpan_core',
            new_name='mpan',
        ),
    ]
