# Generated by Django 5.2.1 on 2025-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterData_handler_app', '0004_rename_mpan_core_meterreading_mpan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='mpan',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
